"""add_todos_table

Revision ID: 23c1143857f2
Revises: a1b2c3d4e5f6
Create Date: 2026-03-14 14:23:25.992185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23c1143857f2'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('todo_id', sa.String(length=36), nullable=False),
    sa.Column('text', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_todos_todo_id'), 'todos', ['todo_id'], unique=True)
    op.drop_index(op.f('ix_draft_revisions_draft_id_rev_num'), table_name='draft_revisions')
    op.create_index(op.f('ix_draft_revisions_draft_id'), 'draft_revisions', ['draft_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_draft_revisions_draft_id'), table_name='draft_revisions')
    op.create_index(op.f('ix_draft_revisions_draft_id_rev_num'), 'draft_revisions', ['draft_id', 'rev_num'], unique=False)
    op.drop_index(op.f('ix_todos_todo_id'), table_name='todos')
    op.drop_table('todos')
    # ### end Alembic commands ###
