"""add_blends_table

Revision ID: 67bb541f5dab
Revises: f4aba5e9a5bd
Create Date: 2026-03-15 13:29:31.409956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67bb541f5dab'
down_revision: Union[str, Sequence[str], None] = 'f4aba5e9a5bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('goal', sa.String(length=512), nullable=False),
    sa.Column('ingredients', sa.JSON(), nullable=False),
    sa.Column('indications', sa.String(length=2000), nullable=False),
    sa.Column('contraindications', sa.String(length=2000), nullable=False),
    sa.Column('compatibility_notes', sa.String(length=2000), nullable=False),
    sa.Column('source_pdf', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blends_name'), 'blends', ['name'], unique=False)
    op.create_index(op.f('ix_blends_slug'), 'blends', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blends_slug'), table_name='blends')
    op.drop_index(op.f('ix_blends_name'), table_name='blends')
    op.drop_table('blends')
    # ### end Alembic commands ###
