"""add_publishing_fields_and_publish_log

Revision ID: 885c1b282bf2
Revises: 23c1143857f2
Create Date: 2026-03-14 18:55:26.952613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '885c1b282bf2'
down_revision: Union[str, Sequence[str], None] = '23c1143857f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publish_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('draft_id', sa.String(length=32), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('error_message', sa.String(length=1000), nullable=False),
    sa.Column('attempt_num', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publish_log_draft_id'), 'publish_log', ['draft_id'], unique=False)
    op.add_column('drafts', sa.Column('scheduled_at', sa.DateTime(), nullable=True))
    op.add_column('drafts', sa.Column('publish_platforms', sa.JSON(), nullable=False, server_default='[]'))
    op.add_column('drafts', sa.Column('external_ids', sa.JSON(), nullable=False, server_default='{}'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drafts', 'external_ids')
    op.drop_column('drafts', 'publish_platforms')
    op.drop_column('drafts', 'scheduled_at')
    op.drop_index(op.f('ix_publish_log_draft_id'), table_name='publish_log')
    op.drop_table('publish_log')
    # ### end Alembic commands ###
