"""add trend_signals and collector_health tables

Revision ID: 8baaa2874213
Revises: b1c2d3e4f5a6
Create Date: 2026-03-17 10:42:07.034643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8baaa2874213'
down_revision: Union[str, Sequence[str], None] = 'b1c2d3e4f5a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collector_health',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_key', sa.String(length=32), nullable=False),
    sa.Column('last_success', sa.DateTime(), nullable=True),
    sa.Column('last_failure', sa.DateTime(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('circuit_open_until', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.String(length=1000), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collector_health_source_key'), 'collector_health', ['source_key'], unique=True)
    op.create_table('trend_signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_key', sa.String(length=32), nullable=False),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.Column('keyword', sa.String(length=255), nullable=False),
    sa.Column('score_raw', sa.Float(), nullable=False),
    sa.Column('velocity', sa.Float(), nullable=False),
    sa.Column('lifecycle_stage', sa.String(length=32), nullable=False),
    sa.Column('convergence_score', sa.Float(), nullable=False),
    sa.Column('sentiment', sa.String(length=16), nullable=False),
    sa.Column('items_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trend_signals_collected_at'), 'trend_signals', ['collected_at'], unique=False)
    op.create_index(op.f('ix_trend_signals_keyword'), 'trend_signals', ['keyword'], unique=False)
    op.create_index(op.f('ix_trend_signals_source_key'), 'trend_signals', ['source_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trend_signals_source_key'), table_name='trend_signals')
    op.drop_index(op.f('ix_trend_signals_keyword'), table_name='trend_signals')
    op.drop_index(op.f('ix_trend_signals_collected_at'), table_name='trend_signals')
    op.drop_table('trend_signals')
    op.drop_index(op.f('ix_collector_health_source_key'), table_name='collector_health')
    op.drop_table('collector_health')
    # ### end Alembic commands ###
