"""add_trend_cards_and_repurpose_groups

Revision ID: 97734efba4e5
Revises: a3331ac4446f
Create Date: 2026-03-22 15:22:30.306722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '97734efba4e5'
down_revision: Union[str, Sequence[str], None] = 'a3331ac4446f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repurpose_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=True),
    sa.Column('source_draft_id', sa.String(length=32), nullable=False),
    sa.Column('core_message', sa.Text(), nullable=False),
    sa.Column('key_points', sa.JSON(), nullable=False),
    sa.Column('target_drafts', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repurpose_groups_group_id'), 'repurpose_groups', ['group_id'], unique=True)
    op.create_index(op.f('ix_repurpose_groups_source_draft_id'), 'repurpose_groups', ['source_draft_id'], unique=False)
    op.create_index(op.f('ix_repurpose_groups_team_id'), 'repurpose_groups', ['team_id'], unique=False)
    op.create_table('trend_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=True),
    sa.Column('keyword', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('strength', sa.Float(), nullable=False),
    sa.Column('lifecycle', sa.String(length=32), nullable=False),
    sa.Column('sentiment', sa.String(length=16), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('suggested_formats', sa.JSON(), nullable=False),
    sa.Column('source_signals', sa.JSON(), nullable=False),
    sa.Column('velocity', sa.Float(), nullable=False),
    sa.Column('convergence', sa.Float(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trend_cards_card_id'), 'trend_cards', ['card_id'], unique=True)
    op.create_index(op.f('ix_trend_cards_keyword'), 'trend_cards', ['keyword'], unique=False)
    op.create_index(op.f('ix_trend_cards_team_id'), 'trend_cards', ['team_id'], unique=False)
    op.alter_column('brand_settings', 'instagram_accounts',
               existing_type=sqlite.JSON(),
               nullable=False,
               existing_server_default=sa.text("'[]'"))
    op.alter_column('brand_settings', 'threads_accounts',
               existing_type=sqlite.JSON(),
               nullable=False,
               existing_server_default=sa.text("'[]'"))
    op.alter_column('brand_settings', 'content_pillars',
               existing_type=sqlite.JSON(),
               nullable=False,
               existing_server_default=sa.text("'[]'"))
    op.create_unique_constraint(None, 'brand_settings', ['team_id'])
    op.create_foreign_key(None, 'brand_settings', 'teams', ['team_id'], ['team_id'])
    op.alter_column('daily_oils', 'context',
               existing_type=sqlite.JSON(),
               nullable=False,
               existing_server_default=sa.text("'{}'"))
    op.create_foreign_key(None, 'drafts', 'teams', ['team_id'], ['team_id'])
    op.create_foreign_key(None, 'mentions', 'teams', ['team_id'], ['team_id'])
    op.create_foreign_key(None, 'plans', 'teams', ['team_id'], ['team_id'])
    op.drop_index('ix_platform_tokens_platform', table_name='platform_tokens')
    op.create_index(op.f('ix_platform_tokens_platform'), 'platform_tokens', ['platform'], unique=False)
    op.create_unique_constraint(None, 'platform_tokens', ['team_id', 'platform'])
    op.create_foreign_key(None, 'platform_tokens', 'teams', ['team_id'], ['team_id'])
    op.create_foreign_key(None, 'post_metrics', 'teams', ['team_id'], ['team_id'])
    op.create_foreign_key(None, 'publish_log', 'teams', ['team_id'], ['team_id'])
    op.create_foreign_key(None, 'saved_blends', 'teams', ['team_id'], ['team_id'])
    op.alter_column('social_trend_posts', 'hashtags',
               existing_type=sqlite.JSON(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('social_trend_posts', 'hashtags',
               existing_type=sqlite.JSON(),
               nullable=True)
    op.drop_constraint(None, 'saved_blends', type_='foreignkey')
    op.drop_constraint(None, 'publish_log', type_='foreignkey')
    op.drop_constraint(None, 'post_metrics', type_='foreignkey')
    op.drop_constraint(None, 'platform_tokens', type_='foreignkey')
    op.drop_constraint(None, 'platform_tokens', type_='unique')
    op.drop_index(op.f('ix_platform_tokens_platform'), table_name='platform_tokens')
    op.create_index('ix_platform_tokens_platform', 'platform_tokens', ['platform'], unique=1)
    op.drop_constraint(None, 'plans', type_='foreignkey')
    op.drop_constraint(None, 'mentions', type_='foreignkey')
    op.drop_constraint(None, 'drafts', type_='foreignkey')
    op.alter_column('daily_oils', 'context',
               existing_type=sqlite.JSON(),
               nullable=True,
               existing_server_default=sa.text("'{}'"))
    op.drop_constraint(None, 'brand_settings', type_='foreignkey')
    op.drop_constraint(None, 'brand_settings', type_='unique')
    op.alter_column('brand_settings', 'content_pillars',
               existing_type=sqlite.JSON(),
               nullable=True,
               existing_server_default=sa.text("'[]'"))
    op.alter_column('brand_settings', 'threads_accounts',
               existing_type=sqlite.JSON(),
               nullable=True,
               existing_server_default=sa.text("'[]'"))
    op.alter_column('brand_settings', 'instagram_accounts',
               existing_type=sqlite.JSON(),
               nullable=True,
               existing_server_default=sa.text("'[]'"))
    op.drop_index(op.f('ix_trend_cards_team_id'), table_name='trend_cards')
    op.drop_index(op.f('ix_trend_cards_keyword'), table_name='trend_cards')
    op.drop_index(op.f('ix_trend_cards_card_id'), table_name='trend_cards')
    op.drop_table('trend_cards')
    op.drop_index(op.f('ix_repurpose_groups_team_id'), table_name='repurpose_groups')
    op.drop_index(op.f('ix_repurpose_groups_source_draft_id'), table_name='repurpose_groups')
    op.drop_index(op.f('ix_repurpose_groups_group_id'), table_name='repurpose_groups')
    op.drop_table('repurpose_groups')
    # ### end Alembic commands ###
