"""add tracked_threads table

Revision ID: af4842639fd7
Revises: d9cd45f03d70
Create Date: 2026-03-17 01:47:27.390859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af4842639fd7'
down_revision: Union[str, Sequence[str], None] = 'd9cd45f03d70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracked_threads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.String(length=64), nullable=False),
    sa.Column('platform', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('author_username', sa.String(length=128), nullable=False),
    sa.Column('text', sa.String(length=4000), nullable=False),
    sa.Column('permalink', sa.String(length=512), nullable=False),
    sa.Column('root_text', sa.String(length=4000), nullable=False),
    sa.Column('keyword_matched', sa.String(length=128), nullable=False),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.Column('reply_count', sa.Integer(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.Column('relevance_reason', sa.String(length=500), nullable=False),
    sa.Column('suggested_action', sa.String(length=32), nullable=False),
    sa.Column('ai_summary', sa.String(length=1000), nullable=False),
    sa.Column('content_angle', sa.String(length=500), nullable=False),
    sa.Column('topic_tags', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('found_at', sa.DateTime(), nullable=False),
    sa.Column('acted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tracked_threads_found_at'), 'tracked_threads', ['found_at'], unique=False)
    op.create_index(op.f('ix_tracked_threads_platform'), 'tracked_threads', ['platform'], unique=False)
    op.create_index(op.f('ix_tracked_threads_status'), 'tracked_threads', ['status'], unique=False)
    op.create_index(op.f('ix_tracked_threads_thread_id'), 'tracked_threads', ['thread_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tracked_threads_thread_id'), table_name='tracked_threads')
    op.drop_index(op.f('ix_tracked_threads_status'), table_name='tracked_threads')
    op.drop_index(op.f('ix_tracked_threads_platform'), table_name='tracked_threads')
    op.drop_index(op.f('ix_tracked_threads_found_at'), table_name='tracked_threads')
    op.drop_table('tracked_threads')
    # ### end Alembic commands ###
