"""add_upload_post_api_key_to_brand_settings

Revision ID: b2efc9c405f9
Revises: 67bb541f5dab
Create Date: 2026-03-15 15:34:24.399035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2efc9c405f9'
down_revision: Union[str, Sequence[str], None] = '67bb541f5dab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brand_settings', sa.Column('upload_post_api_key', sa.String(length=255), nullable=False, server_default=""))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('brand_settings', 'upload_post_api_key')
    # ### end Alembic commands ###
