"""add subscription tables

Revision ID: d0c5055b5d71
Revises: 92e35378794b
Create Date: 2026-03-15 23:38:11.402761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0c5055b5d71'
down_revision: Union[str, Sequence[str], None] = '92e35378794b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promo_codes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('tier', sa.String(length=32), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('max_uses', sa.Integer(), nullable=False),
    sa.Column('uses_count', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promo_codes_code'), 'promo_codes', ['code'], unique=True)
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('tier', sa.String(length=32), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('ends_at', sa.DateTime(), nullable=True),
    sa.Column('promo_code_id', sa.Integer(), nullable=True),
    sa.Column('activated_by', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_telegram_id'), 'subscriptions', ['telegram_id'], unique=False)
    op.create_table('usage_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.String(length=16), nullable=False),
    sa.Column('cards_created', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_id', 'date')
    )
    op.create_index(op.f('ix_usage_logs_telegram_id'), 'usage_logs', ['telegram_id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('tier', sa.String(length=32), nullable=False),
    sa.Column('trial_ends_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('telegram_id')
    )
    # VPS tables (mentions, mention_replies, platform_tokens) intentionally not dropped
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mentions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('mention_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('platform', sa.VARCHAR(length=32), nullable=False),
    sa.Column('external_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('type', sa.VARCHAR(length=32), nullable=False),
    sa.Column('author_username', sa.VARCHAR(length=255), nullable=False),
    sa.Column('author_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('content', sa.VARCHAR(length=4000), nullable=False),
    sa.Column('url', sa.VARCHAR(length=1024), nullable=False),
    sa.Column('context_post', sa.VARCHAR(length=4000), nullable=False),
    sa.Column('received_at', sa.DATETIME(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mentions_status'), 'mentions', ['status'], unique=False)
    op.create_index(op.f('ix_mentions_platform'), 'mentions', ['platform'], unique=False)
    op.create_index(op.f('ix_mentions_mention_id'), 'mentions', ['mention_id'], unique=1)
    op.create_index(op.f('ix_mentions_external_id'), 'mentions', ['external_id'], unique=False)
    op.create_table('mention_replies',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('reply_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('mention_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('tone', sa.VARCHAR(length=32), nullable=False),
    sa.Column('content', sa.VARCHAR(length=2000), nullable=False),
    sa.Column('generated_at', sa.DATETIME(), nullable=False),
    sa.Column('selected', sa.BOOLEAN(), nullable=False),
    sa.Column('published_at', sa.DATETIME(), nullable=True),
    sa.Column('publish_error', sa.VARCHAR(length=1000), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mention_replies_reply_id'), 'mention_replies', ['reply_id'], unique=1)
    op.create_index(op.f('ix_mention_replies_mention_id'), 'mention_replies', ['mention_id'], unique=False)
    op.create_table('platform_tokens',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('platform', sa.VARCHAR(length=32), nullable=False),
    sa.Column('access_token', sa.VARCHAR(length=1024), nullable=False),
    sa.Column('expires_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_tokens_platform'), 'platform_tokens', ['platform'], unique=1)
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_usage_logs_telegram_id'), table_name='usage_logs')
    op.drop_table('usage_logs')
    op.drop_index(op.f('ix_subscriptions_telegram_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_promo_codes_code'), table_name='promo_codes')
    op.drop_table('promo_codes')
    # ### end Alembic commands ###
