"""add_brand_settings

Revision ID: ef8dd552ee6c
Revises: 885c1b282bf2
Create Date: 2026-03-15 13:10:55.838924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef8dd552ee6c'
down_revision: Union[str, Sequence[str], None] = '885c1b282bf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_voice', sa.String(length=4000), nullable=False),
    sa.Column('forbidden_phrases', sa.JSON(), nullable=False),
    sa.Column('base_instructions', sa.String(length=4000), nullable=False),
    sa.Column('target_platforms', sa.JSON(), nullable=False),
    sa.Column('upload_post_user', sa.String(length=255), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('brand_settings')
    # ### end Alembic commands ###
