"""add_approval_workflow_fields_to_drafts

Revision ID: f4aba5e9a5bd
Revises: ef8dd552ee6c
Create Date: 2026-03-15 13:17:10.308458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4aba5e9a5bd'
down_revision: Union[str, Sequence[str], None] = 'ef8dd552ee6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drafts', sa.Column('revision_notes', sa.String(length=2000), nullable=False))
    op.add_column('drafts', sa.Column('published_at', sa.DateTime(), nullable=True))
    op.add_column('drafts', sa.Column('error', sa.String(length=2000), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drafts', 'error')
    op.drop_column('drafts', 'published_at')
    op.drop_column('drafts', 'revision_notes')
    # ### end Alembic commands ###
