"""add api_cost_logs table

Revision ID: f78119590d91
Revises: d0c5055b5d71
Create Date: 2026-03-16 22:12:04.658462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f78119590d91'
down_revision: Union[str, Sequence[str], None] = 'd0c5055b5d71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_cost_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=16), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('context', sa.String(length=128), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_cost_logs_date'), 'api_cost_logs', ['date'], unique=False)
    op.create_index(op.f('ix_api_cost_logs_telegram_id'), 'api_cost_logs', ['telegram_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_cost_logs_telegram_id'), table_name='api_cost_logs')
    op.drop_index(op.f('ix_api_cost_logs_date'), table_name='api_cost_logs')
    op.drop_table('api_cost_logs')
    # ### end Alembic commands ###
